version: "3.8"
services:
  postgres:
    image: postgres:latest
    env_file:
      - ./environment/database.env
    volumes:
      - ./backend/database/schema/:/docker-entrypoint-initdb.d/
  api:
    build: ./backend/api/
    volumes:
      - images_volume:/static/
    env_file:
      - ./environment/database.env
    depends_on:
      - postgres
  nginx:
    build: ./frontend/
    volumes:
      - images_volume:/var/www/html/static/:ro
    ports:
      - 2020:80
volumes:
  images_volume: {}
